// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC57959wJ9_H4ST1vaklOkDmKhpWb0_V3U',
    appId: '1:759695958387:web:1306c02419e9b7888ba506',
    messagingSenderId: '759695958387',
    projectId: 'todo-app-74f55',
    authDomain: 'todo-app-74f55.firebaseapp.com',
    storageBucket: 'todo-app-74f55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwd0NExL9KZQM74651-xBgq5ah0Kxq-FQ',
    appId: '1:759695958387:android:3e333805f51e8e2e8ba506',
    messagingSenderId: '759695958387',
    projectId: 'todo-app-74f55',
    storageBucket: 'todo-app-74f55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCu5BfPvwZRq0ZkKPWN6CGYFwyeb6VJ7A',
    appId: '1:759695958387:ios:9dca41ef2387bf8a8ba506',
    messagingSenderId: '759695958387',
    projectId: 'todo-app-74f55',
    storageBucket: 'todo-app-74f55.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
